name: 'GitHub Pages deployment'
description: 'Deploy static site to GitHub Pages'
inputs:
  # who-to-greet:
  # description: 'Who to greet'
  #   required: true
  #   default: 'World'
  repo:
    description: 'Repo slug'
    required: false
    default: <repo slug>  # TODO correct!
  # github-token:  # TODO use this input name instead?
  token:
    description: 'GitHub token with repo permission'
    required: true
# outputs:
#   time:
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'  # i.e. Docker image to use as the container to run the action
  env:  # i.e. key/value map of environment variables to set in the container environment
    REPO: ${{ inputs.repo }}  # TODO remove?
    TOKEN: ${{ inputs.token }}  # TODO remove?
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.token }}  # TODO keep this secret?
branding:
  icon: 'upload'
  color: 'blue'
