name: 'GitHub Pages deployment'
description: 'Deploy static site to GitHub Pages'
inputs:
  # who-to-greet:
  # description: 'Who to greet'
  #   required: true
  #   default: 'World'
  repo:
    description: 'Repo slug'
    required: false
    default: <repo slug>  # TODO correct!
  # github-token:  # TODO use this input name instead?
  token:
    description: 'GitHub token with repo permission'
    required: true  # TODO required but empty if not provided by the user???
  local-directory:
    description: 'Directory to push to GitHub Pages'
    required: false
    default: 'output'  # TODO check (Pelican's default)!
# outputs:
#   time:
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'  # i.e. Docker image to use as the container to run the action
  env:  # i.e. key/value map of environment variables to set in the container environment
    REPO: ${{ inputs.repo }}
    TOKEN: ${{ inputs.token }}
    LOCAL_DIRECTORY: ${{ inputs.local-directory }}
  args:
    - ${{ inputs.repo }}  # TODO remove?
    - ${{ inputs.token }}  # TODO remove?
branding:
  icon: 'upload'
  color: 'blue'
