name: 'GitHub Pages deployment'
description: 'Deploy static site to GitHub Pages'
inputs:
  # who-to-greet:
  # description: 'Who to greet'
  #   required: true
  #   default: 'World'
  repo:
    description: 'Repo slug'
    required: false
    default: <repo slug>  # TODO correct!
  # github-token:  # TODO use this input name instead?
  token:
    description: 'GitHub token with repo permission'
    required: true  # TODO required but empty if not provided by the user???
  local-directory:
    description: 'Directory to push to GitHub Pages'
    required: false
    default: 'output'  # TODO check (Pelican's default)!
  name:
    description: 'Committer name'
    required: false
    default: ''
  email:
    description: 'Committer email'
    required: false
    default: ''
  temporary-directory:
    description: 'Directory to work in runner'
    required: true
    # default: ${{ runner.temp }}
# outputs:
#   time:
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'  # i.e. Docker image to use as the container to run the action
  env:  # i.e. key/value map of environment variables to set in the container environment
    REPO: ${{ inputs.repo }}
    TOKEN: ${{ inputs.token }}
    LOCAL_DIRECTORY: ${{ inputs.local-directory }}
    NAME: ${{ inputs.name }}
    EMAIL: ${{ inputs.email }}
    TEMPORARY_DIRECTORY: ${{ inputs.temporary-directory }}
    # TEMPORARY_DIRECTORY: ${{ runner.temp }}
  # args:
  #   - ${{ inputs.repo }}
  #   - ${{ inputs.token }}
  #   - ...
branding:
  icon: 'upload'
  color: 'blue'
