# language: minimal  # equivalent to bash, sh or shell  # TODO remove!
language: ruby  # i.e. language support to enable
os: linux  # i.e. build environment operating system
arch: amd64  # i.e. build environment architecture
dist: xenial  # i.e. build environment distribution (Ubuntu Xenial 16.04)


branches:
  only:
    - servant  # i.e. avoid the website to be updated by commits outside of the `servant` branch

# before_install:
#   # TODO complete!
before_install:
  - gem update --system  # c.f. https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html

# install:
#   - bundle install --jobs=3 --retry=3  # Ruby's default



# before_script:
#   # TODO complete!

# script:
#   - rake  # Ruby's default
script: bundle exec jekyll build  # TODO replace?

# deploy:
#   # TODO complete!

# Minimal configuration to deploy static file to GitHub Pages after a successful build.addons:
# (c.f. https://docs.travis-ci.com/user/deployment/pages/)
deploy:
  provider: pages:git  # TODO understand what it means...
  # skip_cleanup: true  # avoid deleting all the files creating during the build (which will probably delete what is trying to be uploaded)  # TODO remove (deprecated)?
  cleanup: true  # avoid deleting all the files creating during the build (which will probably delete what is trying to be uploaded)
  # github_token: $USER_GITHUB_PAGES_TOKEN  # set in the settings page of your repository, as a secure variable
  token: $USER_GITHUB_PAGES_TOKEN  # set in the settings page of your repository, as a secure variable
  on:
    branch: servant  # i.e. target branch used for deployment and only this specific purpose
  local_dir: _site  # i.e. directory to push to GitHub Pages
  repo: balefebvre/balefebvre.github.io  # i.e. repo slug
  target_branch: master  # i.e. branch to push `local_dir` contents to
  keep_history: true  # disable the "force push" behavior to avoid overwriting the history on the target branch  # i.e. create incremental commit instead of doing push force
  # fqdn:  # i.e. set a custom domain for the website
  # project_name:  # Defaults to value of `fqdn` or repo slug, used for metadata.
  # email:  # Optional, committer info, defaults to `deploy@travis-ci.org`.
  # name:  # Optional, committer, defaults to `Deployment Bot`.
  # commiter_from_gh:  # Optional, defaults to `false`. Allows you to use the token’s owner name and email for commit. Overrides `email` and `name` options.
  allow_empty_commit: true  # Optional, defaults to `false`. Enabled if only `keep_history` is `true`.
  # github_url:  # Optional, the URL of the self-hosted GitHub enterprise, defaults to `github.com`.
  verbose: true  # Optional, be verbose about internal steps, defaults to `false`.
  # deployment_file:  # Optional, defaults to `false`, enables creation of deployment-info files.
